/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as staticIdRouteRouteImport } from './routes/(static)/$id/route'
import { Route as dashboardDashboardRouteRouteImport } from './routes/(dashboard)/dashboard/route'
import { Route as staticIdIndexRouteImport } from './routes/(static)/$id/index'
import { Route as dashboardDashboardIndexRouteImport } from './routes/(dashboard)/dashboard/index'
import { Route as ApiWebhookTelegramRouteRouteImport } from './routes/api/webhook/telegram/route'

const staticIdRouteRoute = staticIdRouteRouteImport.update({
  id: '/(static)/$id',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardRouteRoute = dashboardDashboardRouteRouteImport.update({
  id: '/(dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const staticIdIndexRoute = staticIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => staticIdRouteRoute,
} as any)
const dashboardDashboardIndexRoute = dashboardDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardDashboardRouteRoute,
} as any)
const ApiWebhookTelegramRouteRoute = ApiWebhookTelegramRouteRouteImport.update({
  id: '/api/webhook/telegram',
  path: '/api/webhook/telegram',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof dashboardDashboardRouteRouteWithChildren
  '/$id': typeof staticIdRouteRouteWithChildren
  '/api/webhook/telegram': typeof ApiWebhookTelegramRouteRoute
  '/dashboard/': typeof dashboardDashboardIndexRoute
  '/$id/': typeof staticIdIndexRoute
}
export interface FileRoutesByTo {
  '/api/webhook/telegram': typeof ApiWebhookTelegramRouteRoute
  '/dashboard': typeof dashboardDashboardIndexRoute
  '/$id': typeof staticIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)/dashboard': typeof dashboardDashboardRouteRouteWithChildren
  '/(static)/$id': typeof staticIdRouteRouteWithChildren
  '/api/webhook/telegram': typeof ApiWebhookTelegramRouteRoute
  '/(dashboard)/dashboard/': typeof dashboardDashboardIndexRoute
  '/(static)/$id/': typeof staticIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/$id'
    | '/api/webhook/telegram'
    | '/dashboard/'
    | '/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/webhook/telegram' | '/dashboard' | '/$id'
  id:
    | '__root__'
    | '/(dashboard)/dashboard'
    | '/(static)/$id'
    | '/api/webhook/telegram'
    | '/(dashboard)/dashboard/'
    | '/(static)/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardDashboardRouteRoute: typeof dashboardDashboardRouteRouteWithChildren
  staticIdRouteRoute: typeof staticIdRouteRouteWithChildren
  ApiWebhookTelegramRouteRoute: typeof ApiWebhookTelegramRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(static)/$id': {
      id: '/(static)/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof staticIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard': {
      id: '/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/$id/': {
      id: '/(static)/$id/'
      path: '/'
      fullPath: '/$id/'
      preLoaderRoute: typeof staticIdIndexRouteImport
      parentRoute: typeof staticIdRouteRoute
    }
    '/(dashboard)/dashboard/': {
      id: '/(dashboard)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof dashboardDashboardIndexRouteImport
      parentRoute: typeof dashboardDashboardRouteRoute
    }
    '/api/webhook/telegram': {
      id: '/api/webhook/telegram'
      path: '/api/webhook/telegram'
      fullPath: '/api/webhook/telegram'
      preLoaderRoute: typeof ApiWebhookTelegramRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface dashboardDashboardRouteRouteChildren {
  dashboardDashboardIndexRoute: typeof dashboardDashboardIndexRoute
}

const dashboardDashboardRouteRouteChildren: dashboardDashboardRouteRouteChildren =
  {
    dashboardDashboardIndexRoute: dashboardDashboardIndexRoute,
  }

const dashboardDashboardRouteRouteWithChildren =
  dashboardDashboardRouteRoute._addFileChildren(
    dashboardDashboardRouteRouteChildren,
  )

interface staticIdRouteRouteChildren {
  staticIdIndexRoute: typeof staticIdIndexRoute
}

const staticIdRouteRouteChildren: staticIdRouteRouteChildren = {
  staticIdIndexRoute: staticIdIndexRoute,
}

const staticIdRouteRouteWithChildren = staticIdRouteRoute._addFileChildren(
  staticIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  dashboardDashboardRouteRoute: dashboardDashboardRouteRouteWithChildren,
  staticIdRouteRoute: staticIdRouteRouteWithChildren,
  ApiWebhookTelegramRouteRoute: ApiWebhookTelegramRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
